PracticaDjangoSolucion/EjercicioDjango/urls.py
from django.contrib import admin
from django.urls import path
from main import views

urlpatterns = [
    path('ocupaciones_usuarios/',views.mostrar_ocupaciones),
    path('puntuaciones_usuario/',views.mostrar_puntuaciones_usuario),
    path('mejores_peliculas/',views.mostrar_mejores_peliculas),
    path('busqueda_peliculas/',views.mostrar_peliculas_year),
    path('',views.index),
    path('index.html/', views.index),
    path('populate/', views.populateDatabase),
    path('ingresar/', views.ingresar),    
    path('admin/',admin.site.urls),
    ]

PracticaDjangoSolucion/main/models.py
#encoding:utf-8

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Ocupacion(models.Model):
    ocupacionId = models.AutoField(primary_key=True)
    nombre = models.TextField(verbose_name='Ocupación', unique=True)

    def __str__(self):
        return self.nombre
    
    class Meta:
        ordering = ('nombre', )

class Usuario(models.Model):
    idUsuario = models.TextField(primary_key=True)
    edad = models.IntegerField(verbose_name='Edad', help_text='Debe introducir una edad')
    sexo = models.CharField(max_length=1, verbose_name='Sexo', help_text='Debe elegir entre M o F')
    ocupacion = models.ForeignKey(Ocupacion, on_delete=models.SET_NULL, null=True)
    codigoPostal = models.TextField(verbose_name='Código Postal')

    def __str__(self):
        return self.idUsuario
    
    class Meta:
        ordering = ('idUsuario', )

class Categoria(models.Model):
    idCategoria = models.TextField(primary_key=True)
    nombre = models.TextField(verbose_name='Categoría')

    def __str__(self):
        return self.nombre
    
    class Meta:
        ordering =('nombre', )

class Pelicula(models.Model):
    idPelicula = models.TextField(primary_key=True)
    titulo = models.TextField(verbose_name='Título')
    fechaEstreno = models.DateField(verbose_name='Fecha de Estreno', null=True)
    imdbUrl = models.URLField(verbose_name='URL en IMDB')
    categorias = models.ManyToManyField(Categoria)
    puntuaciones = models.ManyToManyField(Usuario, through='Puntuacion')

    def __str__(self):
        return self.titulo
    
    class Meta:
        ordering = ('titulo', 'fechaEstreno', )

class Puntuacion(models.Model):
    PUNTUACIONES = ((1, 'Muy mala'), (2,'Mala'), (3,'Regular'), (4,'Buena'), (5,'Muy Buena'))
    idUsuario = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    idPelicula = models.ForeignKey(Pelicula,on_delete=models.CASCADE)
    puntuacion = models.IntegerField(verbose_name='Puntuación', validators=[MinValueValidator(0), MaxValueValidator(5)], choices=PUNTUACIONES)
    
    def __str__(self):
        return (str(self.puntuacion))
    
    class Meta:
        ordering=('idPelicula','idUsuario', )

PracticaDjangoSolucion/main/forms.py
#encoding:utf-8
from django import forms
   
class UsuarioBusquedaForm(forms.Form):
    idUsuario = forms.CharField(label="Id de Usuario", widget=forms.TextInput, required=True)
    
class PeliculaBusquedaYearForm(forms.Form):
    year = forms.IntegerField(label="Año de publicación", widget=forms.TextInput, required=True)

PracticaDjangoSolucion/main/views.py
#encoding:utf-8
import os

from main.models import Usuario, Ocupacion, Puntuacion, Pelicula, Categoria
from main.forms import  UsuarioBusquedaForm, PeliculaBusquedaYearForm
from django.shortcuts import render
from django.db.models import Avg
from django.http.response import HttpResponseRedirect, HttpResponse
from django.conf import settings
from datetime import datetime

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

path = "data"

#Funcion de acceso restringido que carga los datos en la BD  
@login_required(login_url='/ingresar')
def populateDatabase(request):
    populateOccupations()
    populateGenres()
    u=populateUsers()
    m=populateMovies()
    populateRatings(u,m)  #USAMOS LOS DICCIONARIOS DE USUARIOS Y PELICULAS PARA ACELERAR LA CARGA EN PUNTUACIONES
    logout(request)  # se hace logout para obligar a login cada vez que se vaya a poblar la BD
    return HttpResponseRedirect('/index.html')


def mostrar_ocupaciones(request):
    usuarios= Usuario.objects.all().order_by('ocupacion')
    return render(request, 'ocupacion_usuarios.html',{'usuarios':usuarios, 'STATIC_URL':settings.STATIC_URL})


def mostrar_mejores_peliculas(request):  
    peliculas = Pelicula.objects.annotate(avg_rating=Avg('puntuacion__puntuacion')).order_by('-avg_rating')[:5]
    return render(request, 'mejores_peliculas.html', {'peliculas':peliculas, 'STATIC_URL':settings.STATIC_URL})


def mostrar_peliculas_year(request):
    formulario = PeliculaBusquedaYearForm()
    peliculas = None
    
    if request.method=='POST':
        formulario = PeliculaBusquedaYearForm(request.POST)
        
        if formulario.is_valid():
            peliculas = Pelicula.objects.filter(fechaEstreno__year=formulario.cleaned_data['year'])
            
    return render(request, 'busqueda_peliculas.html', {'formulario':formulario, 'peliculas':peliculas, 'STATIC_URL':settings.STATIC_URL})


def mostrar_puntuaciones_usuario(request):
    formulario = UsuarioBusquedaForm()
    puntuaciones = None
    
    if request.method=='POST':
        formulario = UsuarioBusquedaForm(request.POST)
        
        if formulario.is_valid():
            puntuaciones = Puntuacion.objects.filter(idUsuario = Usuario.objects.get(pk=formulario.cleaned_data['idUsuario']))
            
    return render(request, 'puntuaciones_usuario.html', {'formulario':formulario, 'puntuaciones':puntuaciones, 'STATIC_URL':settings.STATIC_URL})



def index(request):
    return render(request, 'index.html',{'STATIC_URL':settings.STATIC_URL})

def ingresar(request):
    if request.user.is_authenticated:
        return(HttpResponseRedirect('/populate'))
    formulario = AuthenticationForm()
    if request.method=='POST':
        formulario = AuthenticationForm(request.POST)
        usuario=request.POST['username']
        clave=request.POST['password']
        acceso=authenticate(username=usuario,password=clave)
        if acceso is not None:
            if acceso.is_active:
                login(request, acceso)
                return (HttpResponseRedirect('/populate'))
            else:
                return (HttpResponse('<html><body>ERROR: USUARIO NO ACTIVO </body></html>'))
        else:
            return (HttpResponse('<html><body>ERROR: USUARIO O CONTARSE&Ntilde;A INCORRECTOS </body></html>'))
                     
    return render(request, 'ingresar.html', {'formulario':formulario})


def populateOccupations():
    print("Loading occupations...")
    Ocupacion.objects.all().delete()
    
    lista=[]
    fileobj=open(path+"\\u.occupation", "r")
    for line in fileobj.readlines():
        lista.append(Ocupacion(nombre=str(line.strip())))
    fileobj.close()
    Ocupacion.objects.bulk_create(lista)  # bulk_create hace la carga masiva para acelerar el proceso
    
    print("Occupations inserted: " + str(Ocupacion.objects.count()))
    print("---------------------------------------------------------")


def populateGenres():
    print("Loading Movie Genres...")
    Categoria.objects.all().delete()
    
    lista=[]
    fileobj=open(path+"\\u.genre", "r")
    for line in fileobj.readlines():
        rip = str(line.strip()).split('|')
        if len(rip) != 2:
            continue
        lista.append(Categoria(idCategoria=rip[1], nombre=rip[0]))
    fileobj.close()
    Categoria.objects.bulk_create(lista)
    
    print("Genres inserted: " + str(Categoria.objects.count()))
    print("---------------------------------------------------------")


def populateUsers():
    print("Loading users...")
    Usuario.objects.all().delete()
    
    lista=[]
    dict={}
    fileobj=open(path+"\\u.user", "r")
    for line in fileobj.readlines():
        rip = str(line.strip()).split('|')
        if len(rip) != 5:
            continue
        u=Usuario(idUsuario=rip[0], edad=rip[1], sexo=rip[2], ocupacion=Ocupacion.objects.get(nombre=rip[3]), codigoPostal=rip[4])
        lista.append(u)
        dict[rip[0]]=u
    fileobj.close()
    Usuario.objects.bulk_create(lista)
    
    print("Users inserted: " + str(Usuario.objects.count()))
    print("---------------------------------------------------------")
    return(dict)

def populateMovies():
    print("Loading movies...")
    Pelicula.objects.all().delete()
    
    lista_peliculas =[]  # lista de peliculas
    dict_categorias={}  #  diccionario de categorias de cada pelicula (idPelicula y lista de categorias)
    fileobj=open(os.path.join(path, "u.item"), "r")
    for line in fileobj.readlines():
        rip = line.strip().split('|')
        
        date = None if len(rip[2]) == 0 else datetime.strptime(rip[2], '%d-%b-%Y')
        lista_peliculas.append(Pelicula(idPelicula=rip[0], titulo=rip[1], fechaEstreno=date, imdbUrl=rip[4]))
        
        lista_aux=[]
        for i in range(5, len(rip)):
            if rip [i] == '1':
                lista_aux.append(Categoria.objects.get(pk = (i-5)))
        dict_categorias[rip[0]]=lista_aux
    fileobj.close()    
    Pelicula.objects.bulk_create(lista_peliculas)

    dict={}
    for pelicula in Pelicula.objects.all():
        pelicula.categorias.set(dict_categorias[pelicula.idPelicula])
        dict[pelicula.idPelicula]=pelicula
    
    print("Movies inserted: " + str(Pelicula.objects.count()))
    print("---------------------------------------------------------")
    return(dict)

def populateRatings(u,m):
    print("Loading ratings...")
    Puntuacion.objects.all().delete()

    lista=[]
    fileobj=open(path+"\\u.data", "r")
    for line in fileobj.readlines():
        rip = str(line.strip()).split('\t')
        lista.append(Puntuacion(idUsuario=u[rip[0]], idPelicula=m[rip[1]], puntuacion=rip[2]))
    fileobj.close()
    Puntuacion.objects.bulk_create(lista)
    print("Ratings inserted: " + str(Puntuacion.objects.count()))
    print("---------------------------------------------------------")


    

PracticaDjangoSolucion/main/templates/busqueda_peliculas.html
{% extends 'master.html' %}

{% block titulo %} Busqueda de peliculas por fecha {% endblock %}


{% block buscarPeliculasActiva %} uk-active {% endblock %}

{% block paginaActiva %}
	<li class="uk-active"><span>Busqueda de Peliculas</span></li>
{% endblock %}
		    

{% block contenido %} 
    <div class="uk-animation-slide-bottom">
    	<form class="uk-form" id="formulario" method="post" action=''>{% csrf_token %}
    		<fieldset>
    			<legend>Busqueda de Peliculas</legend>
				<input type="text" name="year" id="id_year" placeholder="Anyo de Publicacion"/>
    			<BR><BR>

    			<input class="uk-button" type='submit' value='Realizar Busqueda'/>
    		</fieldset>
    	</form>
	    
	    <hr>

	    {% if peliculas %}
		    <h3> Peliculas del a&ntilde;o:  {{ peliculas|length }}</h3>
		    <dl class="uk-description-list-line">

			{% for row in peliculas %}
			    <dt>{{row.titulo}}</dt>
			    <dd>{{row.fechaEstreno}} | <a target="_blank" href="{{row.imdbUrl}}">{{row.imdbUrl}}</a></dd>
			    <dd> Categorias: 
			    {% for cat in row.categorias.all %}
			    	{{cat.nombre}} 
			    {% endfor %}
			    </dd>		    
			{% endfor %}

			</dl>

		{% endif %}
	</div>
{% endblock %}

PracticaDjangoSolucion/main/templates/index.html
{% extends 'master.html' %}

{% block titulo %} Autor {% endblock %}



{% block contenido %} 
		<div class="autores">
			<div class="uk-grid">
			    <div class="uk-width-medium-1-3 uk-row-first">
			        <div class="uk-panel uk-panel-box">
			        	<h3 class="uk-panel-title">Vicente Carrillo</h3>
			        	<p class="uk-icon-justify uk-icon-envelope">carrillo@us.es</p>
			        </div>
			    </div>
			</div>
		</div>
<hr>
    <div class="uk-animation-fade">
		<article class="uk-article">
		    <h1 class="uk-article-title">EJERCICIO DE DJANGO </h1>
		    <p class="uk-article-meta"></p>
		    <p class="uk-article-lead">Se desea construir una pagina web, que permita recomendar a usuarios peliculas en funcion de las puntuaciones que han dado otros usuarios a las peliculas y los gustos de estos.
Construir el modelo de datos en Django que almacene la informacion siguiente:
a)	Usuario: IdUsuario, Edad, Sexo(M,F), Ocupacion, CodigoPostal.
b)	Pelicula: IdPelicula, Titulo, FechaEstreno, IMDbURL, Categorias.
c)	Categoria: IdCategoria, Nombre.
d)	Ocupacion: Nombre
e)	Puntuacion: Almacena las puntaciones de usuarios a peliculas.
Las puntuaciones son numeros enteros entre 1 y 5.
Poblar la base de datos extrayendo los datos del Dataset100K de Movilens
http://grouplens.org/datasets/movielens/100k/

Se pide construir una web con un menu principal en la parte superior de la ventana, que permita las siguientes opciones:
a)	Mostrar los usuarios (IdUsuario, Edad, CodigoPostal) agrupados por ocupacion.
b)	Mostrar el titulo de las 5 peliculas mejor puntuadas (puntuacion media).
c)	Un formulario que, dado un anyo de estreno, muestre todas las peliculas (titulo) que se hayan estrenado ese anyo.
d)	Un formulario que, dado un idUsuario, muestre todas las peliculas (titulo) que haya puntuado y su puntuacion.
</p>

		    <hr class="uk-article-divider">

		</article>
	</div>
{% endblock %}

PracticaDjangoSolucion/main/templates/ingresar.html
{% extends 'master.html' %}

{% block titulo %} 
	Identifiquese para Poblar la Base de Datos
{% endblock %}   

{% block contenido %} 
    	<form id="formulario" method="post" action=''>{% csrf_token %}
    		<table>{{formulario}}</table>
    		<p><input type='submit' value='Poblar BD'></p>	
    	</form>
{% endblock %}

PracticaDjangoSolucion/main/templates/master.html
<!DOCTYPE html>
<html lang='es'>
  <head>
	<meta charset='utf-8'>

		<link rel="stylesheet" href="{{STATIC_URL}}css/uikit.min.css" />
		<link rel="stylesheet" href="{{STATIC_URL}}css/components/accordion.min.css" />
		<link rel="stylesheet" href="{{STATIC_URL}}css/components/datepicker.min.css" />
        <script src="{{STATIC_URL}}js/jquery.min.js"></script>
        <script src="{{STATIC_URL}}js/uikit.min.js"></script>
        <script src="{{STATIC_URL}}js/components/accordion.min.js"></script>
        <script src="{{STATIC_URL}}js/components/datepicker.min.js"></script>

  </head>
  <body>
  	<div class="uk-container uk-container-center uk-margin-top uk-margin-large-bottom">
	    <h1>EJERCICIO DE DJANGO - MOVIELENS 100K</h1>
	    <nav class="uk-navbar">
		    <ul class="uk-navbar-nav">
		    	<li class="{% block poblarBDActiva %} {% endblock %}"><a href="/populate">Poblar Base de Datos - Acceso Restringido</a></li>
		        <li class="{% block ocupacionesActiva %} {% endblock %}"><a href="/ocupaciones_usuarios">Lista de Usuarios</a></li>
		        <li class="{% block peliculasActiva %} {% endblock %}"><a href="/mejores_peliculas">Mejores Peliculas</a></li>
		        <li class="{% block buscarPeliculasActiva %} {% endblock %}"><a href="/busqueda_peliculas">Buscar Peliculas</a></li>
		        <li class="{% block buscarUsuarioActiva %} {% endblock %}"><a href="/puntuaciones_usuario">Buscar Usuario</a></li>
		        <li><a href="/index.html">Inicio</a></li>
		    </ul>
		</nav>

		<hr>
 		
 		<h1 class="uk-article-title">{% block titulo %} {% endblock %}</h1>

		<div class="contenido">
		{% block contenido %} {% endblock %}
		</div>
	</div>
  </body>
</html>

PracticaDjangoSolucion/main/templates/mejores_peliculas.html
{% extends 'master.html' %}

{% block titulo %} Lista de las 5 Mejores Peliculas {% endblock %}


{% block peliculasActiva %} uk-active {% endblock %}


{% block contenido %} 
    <div class="uk-animation-shake">
	    <dl class="uk-description-list-line">

		{% for row in peliculas %}
		    <dt>{{row.titulo}} | Nota Media: {{row.avg_rating | floatformat:"2"}}/5</dt>
		    <dd>{{row.fechaEstreno}} | <a href="{{row.imdbUrl}}">{{row.imdbUrl}}</a></dd>	
		{% endfor %}

		</dl>
	</div>
{% endblock %}

PracticaDjangoSolucion/main/templates/ocupacion_usuarios.html
{% extends 'master.html' %}

{% block titulo %} Lista de Usuarios {% endblock %}

{% block ocupacionesActiva %} uk-active {% endblock %}


{% block contenido %} 
    <div class="uk-animation-fade">
	    <div class="uk-accordion" data-uk-accordion="{collapse: false}">
	    	{% regroup usuarios by ocupacion as grouped %}
	    	{% for group in grouped %}
		    	<h3 class="uk-accordion-title">Ocupacion: {{group.grouper}} ({{group.list|length}} usuarios)</h3>
		    	<div class="uk-accordion-content">
		    		<ul class="uk-list  uk-list-striped">
		    		{% for user in group.list %}
						<li><strong>Id Usuario:</strong> {{user.idUsuario}} | <strong>Edad:</strong> {{user.edad}} | <strong>Codigo Postal:</strong> {{user.codigoPostal}}</li>
					{% endfor %}
				    </ul>
		    	</div>
	    	{% endfor %}
		</div>
	</div>
{% endblock %}

PracticaDjangoSolucion/main/templates/puntuaciones_usuario.html
{% extends 'master.html' %}

{% block titulo %} Busqueda de puntuaciones de usuario {% endblock %}

{% block buscarUsuarioActiva %} uk-active {% endblock %}
		    

{% block contenido %} 
    <div class="uk-animation-slide-bottom">
    	<form class="uk-form" id="formulario" method="post" action=''>{% csrf_token %}
    		<fieldset>
    			<legend>Busqueda de Usuarios</legend>
    			<input type="text" name="idUsuario" id="id_idUsuario" placeholder="Id del Usuario"/>
    			<br><br>
    			<input class="uk-button" type='submit' value='Realizar Busqueda'/>
    		</fieldset>
    	</form>
	    
	    <hr>

	    {% if puntuaciones %}
		    <h3> Peliculas puntuadas por el usuario:  {{ puntuaciones|length }}</h3>
		    <dl class="uk-description-list-line">

			{% for row in puntuaciones %}
			    <dt>{{row.idPelicula.titulo}}</dt>
			    <dd>Puntuacion: {{row.puntuacion}}/5</dd>
			{% endfor %}

			</dl>

		{% endif %}
	</div>
{% endblock %}