PracticaSistemaRecomendacion0/PracticaRS/urls.py
#encoding:utf-8

from django.urls import path
from django.contrib import admin
from main import views

urlpatterns = [
    path('', views.index),
    path('populate/', views.populateDB),
    path('loadRS', views.loadRS),
    path('recommendedFilmsItems', views.recommendedFilmsItems),
    path('recommendedFilmsUser', views.recommendedFilmsUser),
    path('similarFilms', views.similarFilms),
    path('recommendedUsersFilms', views.recommendedUsersFilms),
    path('search', views.search),
    path('admin/', admin.site.urls),
]

PracticaSistemaRecomendacion0/main/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator,URLValidator


class Occupation(models.Model):
    occupationName = models.CharField(max_length=30)
    def __str__(self):
        return self.occupationName
 
    
class Genre(models.Model):
    genreName = models.CharField(max_length=20) 
    def __str__(self):
        return self.genreName   
    
      
class UserInformation(models.Model):
    age = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    gender = models.CharField(max_length=1, choices=(('F', 'Female'),('M','Male'),))
    occupation = models.ForeignKey(Occupation, on_delete=models.DO_NOTHING)
    zipCode = models.CharField(max_length=8)
    def __str__(self):
        return self.gender+" "+self.zipCode
  
    
class Film(models.Model):
    movieTitle = models.CharField(max_length=100)
    releaseDate = models.DateField(null=True, blank=True)
    releaseVideoDate = models.DateField(null=True, blank=True)
    IMDbURL = models.URLField(validators=[URLValidator()])
    genres = models.ManyToManyField(Genre)
    ratings = models.ManyToManyField(UserInformation, through="Rating")
    def __str__(self):
        return self.movieTitle

    
class Rating(models.Model):
    user = models.ForeignKey(UserInformation, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    rateDate = models.DateField(null=True, blank=True)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    def __str__(self):
        return str(self.rating)

PracticaSistemaRecomendacion0/main/forms.py
# -*- encoding: utf-8 -*-
from django import forms

class UserForm(forms.Form):
    id = forms.CharField(label='User ID')
    
class FilmForm(forms.Form):
    id = forms.CharField(label='Movie ID')

PracticaSistemaRecomendacion0/main/views.py
import shelve
from main.models import UserInformation, Film, Rating
from main.forms import UserForm, FilmForm
from django.shortcuts import render, get_object_or_404
from main.recommendations import  transformPrefs, calculateSimilarItems, getRecommendations, getRecommendedItems, topMatches
from main.populate import populateDatabase


# Funcion que carga en el diccionario Prefs todas las puntuaciones de usuarios a peliculas. Tambien carga el diccionario inverso y la matriz de similitud entre items
# Serializa los resultados en dataRS.dat
def loadDict():
    Prefs={}   # matriz de usuarios y puntuaciones a cada a items
    shelf = shelve.open("dataRS.dat")
    ratings = Rating.objects.all()
    for ra in ratings:
        user = int(ra.user.id)
        itemid = int(ra.film.id)
        rating = float(ra.rating)
        Prefs.setdefault(user, {})
        Prefs[user][itemid] = rating
    shelf['Prefs']=Prefs
    shelf['ItemsPrefs']=transformPrefs(Prefs)
    shelf['SimItems']=calculateSimilarItems(Prefs, n=10)
    shelf.close()
    


    
#  CONJUNTO DE VISTAS

def index(request): 
    return render(request,'index.html')

def populateDB(request):
    populateDatabase() 
    return render(request,'populate.html')

def loadRS(request):
    loadDict()
    return render(request,'loadRS.html')
 
# APARTADO A
def recommendedFilmsUser(request):
    if request.method=='GET':
        form = UserForm(request.GET, request.FILES)
        if form.is_valid():
            idUser = form.cleaned_data['id']
            user = get_object_or_404(UserInformation, pk=idUser)
            shelf = shelve.open("dataRS.dat")
            Prefs = shelf['Prefs']
            shelf.close()
            rankings = getRecommendations(Prefs,int(idUser))
            recommended = rankings[:2]
            films = []
            scores = []
            for re in recommended:
                films.append(Film.objects.get(pk=re[1]))
                scores.append(re[0])
            items= zip(films,scores)
            return render(request,'recommendationItems.html', {'user': user, 'items': items})
    form = UserForm()
    return render(request,'search_user.html', {'form': form})

# APARTADO B
def recommendedFilmsItems(request):
    if request.method=='GET':
        form = UserForm(request.GET, request.FILES)
        if form.is_valid():
            idUser = form.cleaned_data['id']
            user = get_object_or_404(UserInformation, pk=idUser)
            shelf = shelve.open("dataRS.dat")
            Prefs = shelf['Prefs']
            SimItems = shelf['SimItems']
            shelf.close()
            rankings = getRecommendedItems(Prefs, SimItems, int(idUser))
            recommended = rankings[:2]
            films = []
            scores = []
            for re in recommended:
                films.append(Film.objects.get(pk=re[1]))
                scores.append(re[0])
            items= zip(films,scores)
            return render(request,'recommendationItems.html', {'user': user, 'items': items})
    form = UserForm()
    return render(request,'search_user.html', {'form': form})

# APARTADO C
def similarFilms(request):
    film = None
    if request.method=='GET':
        form = FilmForm(request.GET, request.FILES)
        if form.is_valid():
            idFilm = form.cleaned_data['id']
            film = get_object_or_404(Film, pk=idFilm)
            shelf = shelve.open("dataRS.dat")
            ItemsPrefs = shelf['ItemsPrefs']
            shelf.close()
            recommended = topMatches(ItemsPrefs, int(idFilm),n=3)
            films = []
            similar = []
            for re in recommended:
                films.append(Film.objects.get(pk=re[1]))
                similar.append(re[0])
            items= zip(films,similar)
            return render(request,'similarFilms.html', {'film': film,'films': items})
    form = FilmForm()
    return render(request,'search_film.html', {'form': form})

# APARTADO D
def recommendedUsersFilms(request):
    if request.method=='GET':
        form = FilmForm(request.GET, request.FILES)
        if form.is_valid():
            idFilm = form.cleaned_data['id']
            film = get_object_or_404(Film, pk=idFilm)
            shelf = shelve.open("dataRS.dat")
            Prefs = shelf['ItemsPrefs']
            shelf.close()
            rankings = getRecommendations(Prefs,int(idFilm))
            recommended = rankings[:3]
            films = []
            scores = []
            for re in recommended:
                films.append(UserInformation.objects.get(pk=re[1]))
                scores.append(re[0])
            items= zip(films,scores)
            return render(request,'recommendationUsers.html', {'film': film, 'items': items})
    form = FilmForm()
    return render(request,'search_film.html', {'form': form})
#APARTADO E
def search(request):
    if request.method=='GET':
        form = UserForm(request.GET, request.FILES)
        if form.is_valid():
            idUser = form.cleaned_data['id']
            user = get_object_or_404(UserInformation, pk=idUser)
            return render(request,'ratedFilms.html', {'usuario':user})
    form=UserForm()
    return render(request,'search_user.html', {'form':form })

PracticaSistemaRecomendacion0/main/templates/header.html
<header>
<nav>
	<ul>
		<li><a href="/">Inicio</a></li>
		<li><a href="/populate">Poblar la Base de Datos</a></li>
		<li><a href="/loadRS">Cargar el Sistema de Recomendacion</a></li>
		<li><a href="/recommendedFilmsUser">Recomienda dos Peliculas a un Usuario - RS Basado en Usuarios</a></li>
		<li><a href="/recommendedFilmsItems">Recomienda dos Peliculas a un Usuario - RS Basado en Items</a></li>
		<li><a href="/similarFilms">Tres Peliculas que mas se parecen a otra</a></li>
		<li><a href="/recommendedUsersFilms">Recomienda tres Usuarios a una Pelicula</a></li>		
		<li><a href="/search">Peliculas puntuadas por un Usuario</a></li>
	</ul>
</nav>
</header>

PracticaSistemaRecomendacion0/main/templates/index.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Bienvenido al Sistema de Recomendacion de Movielens!!!</h1> 
<p>
Se desea construir una pagina web, que permita recomendar a usuarios peliculas en funcion de las puntuaciones que han dado otros usuarios a las peliculas y los gustos de estos.
Construir el modelo de datos en Django que almacene la informacion siguiente:

a)	Usuario: Id, Edad, Sexo(M,F), Ocupacion, CodigoPostal.
b)	Pelicula: Id, Titulo, FechaEstreno, FechaEstrenoVideo, IMDbURL, Categorias.
c)	Puntuacion: Puntacion de usuario a pelicula, y fecha/hora en que se produjo.
Las puntuaciones son numericas entre 1 y 5.

Poblar la base de datos extrayendo los datos del Dataset100K de Movilens(u.data, u.user, u.item, u.genre, u.occupation): https://grouplens.org/datasets/movielens/100k/


Se pide construir una web con un menu principal, en la parte superior de la ventana, que permita las siguientes opciones:

a)	Dado un usuario (Id), mostrar todas las peliculas que ha puntuado (Titulo) y su puntuacion.
b)	Dado un usuario (Id), le recomiende dos peliculas que no haya puntuado (Titulo). Usando un sistema de recomendacion de tipo filtrado colaborativo basado en items.
c)	Dado un usuario (Id), le recomiende dos peliculas que no haya puntuado (Titulo). Usando un sistema de recomendacion de tipo filtrado colaborativo basado en usuarios.
d)	Dada una pelicula (Id), mostrar tres usuarios a los que se le recomendaria.
e)	Dada una pelicula (Id), mostrar las tres peliculas (Titulo) que mas se le parecen.
</p>
</body>
</html>

PracticaSistemaRecomendacion0/main/templates/loadRS.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Datos Cargados en el Sistema de Recomendacion</h1>
</body>
</html>

PracticaSistemaRecomendacion0/main/templates/populate.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Base de Datos Cargada</h1>
</body>
</html>

PracticaSistemaRecomendacion0/main/templates/ratedFilms.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
{% include 'header.html' %}
<section>
<h1>Peliculas y Puntuaciones para el Usuario {{usuario.id}}</h1>
{% for rating in usuario.rating_set.all %}
<ul>Movie: {{rating.film.movieTitle}} - Rating: {{rating.rating}}</ul>
{% empty %}
<h2> El Usuario no ha puntuado ninguna Pelicula </h2>
{% endfor %}
</section>
</body>
</html>

PracticaSistemaRecomendacion0/main/templates/recommendationItems.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Peliculas Recomendadas para el Usuario {{user.id}}</h1>
{% for item, score in items %}
<ul>
<li>Title: {{item.movieTitle}}  Score:{{score | floatformat:"2"}}</li>
</ul>
{% empty %}
<h2> Insufficient user data </h2>
{% endfor %}
</body>
</html>

PracticaSistemaRecomendacion0/main/templates/recommendationUsers.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
{% include 'header.html' %}
<h1>Usuarios Recomendados para la Pelicula {{film.movieTitle}}</h1>
{% for item, score in items %}
<ul>
<li>User ID:{{item.id}}   Edad:{{item.age}}  CP:{{item.zipCode}}   Score: {{score | floatformat:"2"}}</li>
</ul>
{% empty %}
<h2> Insuficientes datos </h2>
{% endfor %}
</body>
</html>

PracticaSistemaRecomendacion0/main/templates/search_film.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
<header>
{% include 'header.html' %}

<h1>Buscar Pelicula</h1>
<form id='form' method='get' action=''>
{{form.as_p}}
<p><input type='submit' value='Confirm'/></p>
</form>

</body>
</html>

PracticaSistemaRecomendacion0/main/templates/search_user.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
<header>
{% include 'header.html' %}

<h1>Buscar Usuario</h1>
<form id='form' method='get' action=''>
{{form.as_p}}
<p><input type='submit' value='Confirm'/></p>
</form>

</body>
</html>

PracticaSistemaRecomendacion0/main/templates/similarFilms.html
<html>
<head>
<title>Sistema de Recomendacion - Movielens</title>
</head>
<body>
{% include 'header.html' %}
<section>
<h1>Tres Peliculas que mas se parecen a {{film.movieTitle}} son:</h1>
<l>
{% for f, s in films %}
<li>Title: {{f.movieTitle}}   Similarity: {{s | floatformat:"2"}}</li>
{% endfor %}
</l>
</section>
</body>
</html>